# Generated by Django 5.2.7 on 2025-10-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_product',
            name='type',
        ),
    ]
