# Generated by Django 5.2.7 on 2025-10-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_remove_tbl_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_productsize',
            old_name='productsize',
            new_name='productcolor',
        ),
    ]
