# Generated by Django 5.2.7 on 2025-10-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_tbl_productsize_product_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_productsize',
            name='product_amount',
            field=models.CharField(max_length=30),
        ),
    ]
