# Generated by Django 5.2.7 on 2025-10-24 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=30)),
                ('user_contact', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=30)),
                ('user_status', models.IntegerField(default=0)),
                ('user_doj', models.DateField(auto_now_add=True)),
                ('user_gender', models.CharField(max_length=30)),
                ('user_photo', models.FileField(upload_to='Assets/User/Photo/')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_deliveryboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryboy_name', models.CharField(max_length=30)),
                ('deliveryboy_email', models.CharField(max_length=30)),
                ('deliveryboy_password', models.CharField(max_length=30)),
                ('deliveryboy_contact', models.CharField(max_length=30)),
                ('deliveryboy_status', models.IntegerField(default=0)),
                ('deliveryboy_idproof', models.FileField(upload_to='Assets/Deliveryboy/Idproof/')),
                ('deliveryboy_licence', models.FileField(upload_to='Assets/Deliveryboy/Licence/')),
                ('deliveryboy_photo', models.FileField(upload_to='Assets/Deliveryboy/Photo/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=30)),
                ('seller_email', models.CharField(max_length=30)),
                ('seller_password', models.CharField(max_length=30)),
                ('seller_address', models.CharField(max_length=150)),
                ('seller_slogan', models.CharField(max_length=100)),
                ('seller_status', models.IntegerField(default=0)),
                ('seller_photo', models.FileField(upload_to='Assets/Seller/Photo/')),
                ('seller_proof', models.FileField(upload_to='Assets/Seller/Proof/')),
                ('seller_logo', models.FileField(upload_to='Assets/Seller/Logo/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
